services:

  backend:
    build: ./backend/
    container-name: control-service-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio

  client:
    build: ./client/controlsystem
    container_name: control-service-client
    ports:
      - "80:80"

  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio:RELEASE.2025-04-03T14-56-28Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" 
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: